# test
server:
  port: 8090
logging:
  config: classpath:log4j2-dev.xml
arex:
  storage:
    service:
      url: http://10.118.1.217:8093
  schedule:
    service:
      url: http://10.118.1.217:8092
  mongo:
    uri: mongodb://arex:password@10.118.1.217:27017/arex_storage_db
  redis:
    uri: redis://10.118.1.217:6379/