# test
logging.config=classpath:log4j2-dev.xml
arex.storage.service.url=http://10.5.153.1:8093
arex.schedule.service.url=http://10.5.153.1:8092
arex.mongo.uri=mongodb://arex:iLoveArex@10.5.153.1:27017/arex_storage_db
arex.redis.uri=redis://10.5.153.1:6379/
arex.jwt.secret=arex
